os: linux
language: python

python:
    - "3.8"

install:
    - pip install pyaml jsonschema

script:
    - python3 --version
    - ./pre-commit --all # checking all PKGBUILD

jobs:
    fast_finish: true
