language: python

python:
    - "3.6"

# Use container-based infrastructure for quicker build start-up
sudo: false

install:
    - pip install pyaml

script:
    - python3 --version
    - ./pre-commit --all --no-srcinfo # checking all PKGBUILD

matrix:
    fast_finish: true
