maintainers:
- github: lilydjwg

build_prefix: extra-x86_64

update_on:
- use_max_tag: true
  vcs: git+http://repo.or.cz/socat.git
  from_pattern: tag-(.*)-b(\d)
  to_pattern: \1_b\2
- alias: readline
