maintainers:
- github: lilydjwg
build_prefix: archlinuxcn-x86_64
update_on:
- archpkg: sysdig
  strip-release: true
- cmd: LANG=C pacman --dbpath ~/.lilac/pacmandb -Si linux-lily | awk '$1 == "Version" { print $3 }'
- alias: protobuf
- alias: jsoncpp
